
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8765
spring:
  application:
    name: feign-consumer
  # thymeleaf
  thymeleaf:
    cache: false #开发时关闭缓存,不然没法看到实时页面


# hystrix
feign:
  hystrix:
    enabled: true



